set -g default-terminal "screen-256color"
set-option -g default-command "reattach-to-user-namespace -l bash"

unbind C-b
set-option -g prefix `
bind ` send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind-key R source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

bind h select-pane -L
bind l select-pane -R
bind j select-pane -D
bind k select-pane -U

set -sg escape-time 0

set -g base-index 1
setw -g pane-base-index 1

set-option -g mouse on
bind-key -T root MouseDown1Pane select-pane -t =

set -sg escape-time 0

set-option -sa terminal-overrides ",xterm*:Tc"
set-option -sa terminal-overrides ",screen*:Tc"

setw -g automatic-rename on
set -g renumber-windows on

unbind -T copy-mode-vi MouseDragEnd1Pane

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Capture pane and open in Vim
bind-key C-c run 'FILE=/tmp/tmux-capture-$(date +%Y%m%d%H%M%S).txt; tmux capture-pane -J -S -102400 -p > $FILE; tmux new-window "reattach-to-user-namespace vim $FILE"'
bind-key M-c run "screencapture -l$(osascript -e 'tell app \"iTerm\" to id of window 1') -x -o -P /tmp/$(date +%Y%m%d-%H%M%S).png"

bind-key -n 'M-`' run "tmux split-window -p 40 'tmux send-keys -t #{pane_id} \"$(locate / | fzf -m | paste -sd\\  -)\"'"
